enableGlobalCache: false
# yarnPath: .yarn/releases/yarn-4.0.2.cjs

enableHardenedMode: false

enableImmutableInstalls: false

enableMirror: true
# npmRegistryServer: http://localhost:4873/

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - win32
    - win64

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-4.0.2.cjs
