enableGlobalCache: false
enableImmutableInstalls: false
enableHardenedMode: false
enableMirror: true
npmRegistryServer: http://localhost:4873/
unsafeHttpWhitelist: ["localhost"]

nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.0.2.cjs
