storage: storage
plugins: plugins
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    proxy: npmjs
no_proxy: localhost,127.0.0.1
logs: { type: stdout, format: pretty, level: http }
